# Generated by Django 5.0.4 on 2024-04-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.IntegerField(max_length=12)),
                ('address', models.TextField(max_length=100)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
